### 회원가입
POST localhost:8080/api/auth/signup
Content-Type: application/json

{
  "userName" : "33",
  "userEmail" : "1131@naver.com",
  "password": "test",
  "gender" : "MAN",
  "type" : "GENERAL"
}

### 로그인
POST localhost:8080/api/auth/login
Content-Type: application/json

{
  "email" : "1131@naver.com",
  "password": "test"
}
> {%
 client.global.set("authorizationToken", "Bearer " + response.body.data.accessToken);
 client.log("AUth Token :" + client.global.get("authorizationToken"));
 %}

### 회원삭제
