### 단일 컨텐츠 불러오기
GET localhost:8080/api/content/1
Content-Type: application/json
Authorization: {{ authorizationToken }}


### 컨텐츠 저장
POST localhost:8080/api/content
Content-Type: application/json
Authorization: {{ authorizationToken }}

{
  "content" : "444",
  "payType" : "PAY",
  "amount": 110,
  "minorWorkType" : "ADULT_WORK"
}

### 작품 평가
POST localhost:8080/api/content/evaluation
Content-Type: application/json
Authorization: {{ authorizationToken }}

{
  "evaluationType" : "LIKE",
  "comment" : "댓글테스트",
  "contentId": 1
}


### 작품 payType 변경
PUT localhost:8080/api/content/1/payType
Content-Type: application/json
Authorization: {{ authorizationToken }}

{
  "payType" : "PAY",
  "amount" : 200
}
### 컨텐츠 로그 확인
GET localhost:8080/api/content/1/user-log
Authorization: {{ authorizationToken }}

### 작품 랭킹

GET localhost:8080/api/content/ranking
Content-Type: application/json
Authorization: {{ authorizationToken }}