### 컨텐츠 저장
POST localhost:8080/api/content
Content-Type: application/json
Authorization: {{ authorizationToken }}

{
  "content" : "33",
  "payType" : "PAY",
  "amount": 101,
  "minorWorkType" : "ADULT_WORK"
}

### 작품 평가
POST localhost:8080/api/content/evaluation
Content-Type: application/json
Authorization: {{ authorizationToken }}

{
  "evaluationType" : "33",
  "comment" : "PAY",
  "contentId": 101
}